server:
  port: 10003
spring:
   profiles:
     active: prod
---
spring:
  profiles: prod
data:
  env:
    user: aaa
    password: aaa
---
spring:
  profiles: dev
data:
  env:
    user: aaaaaaaaa
    password: aaaaaaaaa